from pathlib import Path

p = Path('src/super-gui.js')
s = p.read_text()
s = s.replace("      this._editorWindow = null;", "      this._editorWindow = null;\n      this._editorDock = null;\n      this._editorFrame = null;\n      this._editorLauncher = null;")
old = '''    openEditor() {\n      if (this._editorWindow && !this._editorWindow.closed) { this._editorWindow.focus(); return; }\n      const win = window.open('', 'SuperGUIEditor', 'width=1360,height=880,resizable=yes');\n      if (!win) { alert('SuperGUI: popup blocked.'); return; }\n      win.document.open();\n      win.document.write(SUPERGUI_EDITOR_HTML);\n      win.document.close();\n      this._editorWindow = win;\n    }\n'''
new = '''    openEditor() {\n      this._ensureEmbeddedEditor();\n      this._restoreEmbeddedEditor();\n    }\n\n    _ensureEmbeddedEditor() {\n      if (this._editorDock && this._editorDock.isConnected) return;\n\n      const dock = document.createElement('div');\n      dock.id = 'supergui-editor-dock';\n      dock.style.cssText = [\n        'position:fixed',\n        'left:12px',\n        'right:12px',\n        'top:12px',\n        'bottom:12px',\n        'z-index:2147483000',\n        'background:#1b1e29',\n        'border:1px solid #3a3f52',\n        'border-radius:12px',\n        'box-shadow:0 18px 60px rgba(0,0,0,.55)',\n        'overflow:hidden',\n        'display:none'\n      ].join(';');\n\n      const frame = document.createElement('iframe');\n      frame.title = 'SuperGUI Editor';\n      frame.style.cssText = 'width:100%;height:100%;border:0;display:block;background:#1b1e29;';\n      dock.appendChild(frame);\n      document.body.appendChild(dock);\n\n      const launcher = document.createElement('button');\n      launcher.id = 'supergui-editor-launcher';\n      launcher.textContent = 'SuperGUI';\n      launcher.title = 'Restore SuperGUI Editor';\n      launcher.style.cssText = [\n        'position:fixed',\n        'right:16px',\n        'bottom:16px',\n        'z-index:2147483001',\n        'display:none',\n        'padding:8px 12px',\n        'border-radius:999px',\n        'border:1px solid #7180ff',\n        'background:#5B6EE1',\n        'color:#fff',\n        'font:600 12px sans-serif',\n        'cursor:pointer',\n        'box-shadow:0 8px 24px rgba(0,0,0,.35)'\n      ].join(';');\n      launcher.addEventListener('click', () => this._restoreEmbeddedEditor());\n      document.body.appendChild(launcher);\n\n      this._editorDock = dock;\n      this._editorFrame = frame;\n      this._editorLauncher = launcher;\n\n      const doc = frame.contentDocument;\n      doc.open();\n      doc.write(SUPERGUI_EDITOR_HTML);\n      doc.close();\n      this._wireEmbeddedEditorChrome();\n    }\n\n    _wireEmbeddedEditorChrome() {\n      const frame = this._editorFrame;\n      if (!frame) return;\n      const doc = frame.contentDocument;\n      if (!doc) return;\n      const min = doc.getElementById('btnMin');\n      const close = doc.getElementById('btnClose');\n      if (close) close.style.display = 'none';\n      if (min) {\n        min.title = 'Minimize editor';\n        min.onclick = (e) => { e.preventDefault(); this._minimizeEmbeddedEditor(); };\n      }\n    }\n\n    _minimizeEmbeddedEditor() {\n      if (this._editorDock) this._editorDock.style.display = 'none';\n      if (this._editorLauncher) this._editorLauncher.style.display = 'block';\n    }\n\n    _restoreEmbeddedEditor() {\n      if (this._editorDock) this._editorDock.style.display = 'block';\n      if (this._editorLauncher) this._editorLauncher.style.display = 'none';\n    }\n'''
if old not in s:
    raise SystemExit('openEditor block not found')
s = s.replace(old, new)
p.write_text(s)

p = Path('src/editor/editor-template.js')
s = p.read_text()
s = s.replace("  var ext = window.opener && window.opener.__superGUIInstance;", "  var ext = (window.parent && window.parent.__superGUIInstance) || (window.opener && window.opener.__superGUIInstance);")
s = s.replace("  <button id=\"btnClose\" class=\"chrome danger\" title=\"Close\">×</button>", "  <button id=\"btnClose\" class=\"chrome danger\" title=\"Close\" style=\"display:none\">×</button>")
p.write_text(s)
